# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:52
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['ip']},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['port']},
        ),
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['host', 'creation_date']},
        ),
        migrations.AddField(
            model_name='port',
            name='privileged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='host',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='port',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='port',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='port',
            name='port',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scan',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Host', unique_for_date='creation_date'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date modified'),
        ),
    ]
