# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_port_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='protocol',
            field=models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=20),
        ),
    ]
