# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_port_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='result',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='scan',
            name='state',
            field=models.CharField(choices=[('todo', 'To do'), ('pending', 'Pending'), ('wip', 'Work in progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
