# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0006_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('command', models.CharField(max_length=150)),
                ('result', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('todo', 'To do'), ('pending', 'Pending'), ('wip', 'Work in progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('error', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
